/**:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    left_gripper_controller:
      type: forward_command_controller/ForwardCommandController

    right_gripper_controller:
      type: forward_command_controller/ForwardCommandController

/**/left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      openarm_left_joint1: {trajectory: 0.1, goal: 0.1}
      openarm_left_joint2: {trajectory: 0.1, goal: 0.1}
      openarm_left_joint3: {trajectory: 0.1, goal: 0.1}
      openarm_left_joint4: {trajectory: 0.1, goal: 0.1}
      openarm_left_joint5: {trajectory: 0.1, goal: 0.1}
      openarm_left_joint6: {trajectory: 0.1, goal: 0.1}
      openarm_left_joint7: {trajectory: 0.1, goal: 0.1}

/**/right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      openarm_right_joint1: {trajectory: 0.1, goal: 0.1}
      openarm_right_joint2: {trajectory: 0.1, goal: 0.1}
      openarm_right_joint3: {trajectory: 0.1, goal: 0.1}
      openarm_right_joint4: {trajectory: 0.1, goal: 0.1}
      openarm_right_joint5: {trajectory: 0.1, goal: 0.1}
      openarm_right_joint6: {trajectory: 0.1, goal: 0.1}
      openarm_right_joint7: {trajectory: 0.1, goal: 0.1}

/**/left_forward_position_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: position

/**/right_forward_position_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: position

/**/left_gripper_controller:
  ros__parameters:
    joints:
      - openarm_left_finger_joint1
    interface_name: position

/**/right_gripper_controller:
  ros__parameters:
    joints:
      - openarm_right_finger_joint1
    interface_name: position
