# Copyright 2025 Enactic, Inc.
# Copyright 2024 Stogl Robotics Consulting UG (haftungsbeschränkt)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    left_forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: position_controllers/GripperActionController

    right_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_gripper_controller:
      type: position_controllers/GripperActionController


left_forward_position_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

left_forward_velocity_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity

left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 50.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

left_gripper_controller:
  ros__parameters:
    joint: openarm_left_finger_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position


right_forward_position_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

right_forward_velocity_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity

right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 50.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

right_gripper_controller:
  ros__parameters:
    joint: openarm_right_finger_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position