# Default initial positions for openarm's ros2_control fake system

initial_positions:
  openarm_left_finger_joint1: 0
  openarm_left_joint1: 0
  openarm_left_joint2: 0
  openarm_left_joint3: 0
  openarm_left_joint4: 0
  openarm_left_joint5: 0
  openarm_left_joint6: 0
  openarm_left_joint7: 0
  openarm_right_finger_joint1: 0
  openarm_right_joint1: 0
  openarm_right_joint2: 0
  openarm_right_joint3: 0
  openarm_right_joint4: 0
  openarm_right_joint5: 0
  openarm_right_joint6: 0
  openarm_right_joint7: 0