# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - openarm_arm_controller
    - gripper_controller

  openarm_arm_controller:
    type: FollowJointTrajectory
    joints:
      - rev1
      - rev2
      - rev3
      - rev4
      - rev5
      - rev6
      - rev7
  gripper_controller:
    type: GripperCommand
    joints:
      - left_pris1
    action_ns: gripper_cmd
    default: true