# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_controller:
      type: position_controllers/GripperActionController


    openarm_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    joint: left_pris1
openarm_arm_controller:
  ros__parameters:
    joints:
      - rev1
      - rev2
      - rev3
      - rev4
      - rev5
      - rev6
      - rev7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity